# Generated by Django 2.2.5 on 2019-09-12 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20190912_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='dept',
            field=models.CharField(default='ENTC', max_length=10),
        ),
        migrations.AddField(
            model_name='subjects',
            name='year',
            field=models.CharField(default='BE', max_length=10),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='subject_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Subjects'),
        ),
    ]
